### ISSUE TITLE
FEATURE REQUEST: Change at every key pressed

### ISSUE THREAD

**Issue by SoulKa** [zanza00/random-theme-switcher#11]
Hi,
I would love to have the theme changed after every key that was pressed while coding.
Greetings, SoulKa

**Comment by Denis-net** [comment]
Hi @SoulKa ! 😊👋🏻

I have opened a pull request for switching the theme once a day.
Now I have improved my design based on your request.

The modes will be:

manual,
startup,
daily,
interval,
typing

When `typing` the theme will be changed when you'll type something.
Hope he will find time to merge it. 🤞🏻

Maybe In your scenario you could try for few minutes (i guess) [this program too](https://www.trisunsoft.com/key-music.htm) 😂

Happy Halloween ! 🧛🏻‍♂️

**Comment by SoulKa** [comment]
@Denis-net Awesome! Thanks for the fast implementation and Happy After-Halloween :D

**Comment by SoulKa** [comment]
Love this feature! Great work!
