### ISSUE TITLE
Feature Request: Starred Theme List

### ISSUE THREAD

**Issue by Denis-net** [zanza00/random-theme-switcher#14]
Hey @zanza00 !

It would be cool to have in the config file a key like this:
``` JSON
{
"starredThemeList":[
["Material Theme", 0.4],
["Netflix Theme", 0.3]
]
}
```

or

``` JSON
{
"starredThemeList":[
["Material Theme", 4],
["Netflix Theme", 1]
]
}
```

where there is a percentage or 1-to-5-star range linked to each theme that influences the random theme generations.

**Comment by zanza00** [comment]
I don't really like this idea, we need to keep in sync two lists that the user can edit. Also how would incrementing or decrementing should happen?

I am worried that this would add a lot of complexity for very little improvement, if you don't like a theme you can use the the key combo or remove it from the list.

What do you think?

**Comment by Denis-net** [comment]
You are right: mantaining two lists is a pain.
What about improving the current one ?

``` JSON
  "randomThemeSwitcher.themeList": [
        ["2077", 1],
        ["Absent (rainglow)", 2],
        ["Absent Contrast (rainglow)", 1],
        ["Abyss", 1],
]
```
The old list will be converted into this one, where each theme has a weight of 1.
If you like particularly a theme you can set it to an higher value or `randomThemeSwitcher.(promote/demote)Theme`.

The feature increases the possibilities of a theme to appear, while still allowing to select other listed themes as well.

I don't personally need this one, but others might.

**Comment by ghost** [comment]
> I don't personally need this one, but others might.

For this reason I am closing it, until it becomes the most requested feature.😉
