### ISSUE TITLE
Feature Request: Detect when the theme changes and if ! present ask for adding it

### ISSUE THREAD

**Issue by Denis-net** [zanza00/random-theme-switcher#18]
Hey @zanza00 !😊👋🏻

When users download and try a new Theme could be interesting to show a `vscode.window.showMessageInfo` that says: "Theme set to `${ThemeName}`, would you like to add it to the randomThemeList ?".

When the `vscode.workspace.onDidChangeConfiguration` event fires, we can check the theme: 

``` Typescript
vscode.workspace.onDidChangeConfiguration((event) => {
	if (event.affectsConfiguration('workbench.colorTheme')) {
                var themeName = vscode.workspace.getConfiguration().get('workbench.colorTheme');
                if(!themeList.includes(themeName)){
                    vscode.window.showInformationMessage(`Theme set to "${themeName}",\nwould you like to add it to the randomThemeList ?`, `Yes`,`No`).then((res)=>{
                        if(res === 'Yes')
                            themeList.push(themeName)
                    })
                }
	}
}),
```

What do you think about it ?

[Optional]
Some extension contains theme pack, so a smart button could be added `add the whole pack`: when selected we could search across the installed extension the one that contains the selected `themeName`

**Comment by zanza00** [comment]
That is a neat idea, when I install a new theme i would like to add it to the list of random ones 👍

**Comment by Denis-net** [comment]
Hello @zanza00  !

While you were away i helped in the #19 issue and then i opened a PR containing a small fix, plus I implemented this feature and seems to work pretty well.
Feel free to give it try when you'll have time.

Good evening ! 😊👋🏼

**Comment by ghost** [comment]
I'm closing this because this was merged into the new version 🔝
