### ISSUE TITLE
Feature Request About `Theme: Copy all installed themes in settings`

### ISSUE THREAD

**Issue by Denis-net** [zanza00/random-theme-switcher#8]
Hey @zanza00 !
I was thinking : what about displaying a quickpick with these options : Ligth, Dark, Both

Not sure how easy can be distinguish between dark, light themes but I think will be very usefull to user that want to download themes and add only one side (darkside in my case, ligth in other, both by default) of them.

Maybe using regexes ?

**Comment by zanza00** [comment]
Hi Denis,

inside the theme object there is a property that specify whether is a light or dark theme. It's definitely doable. I will do it when I have the time :)

**Comment by Denis-net** [comment]
Hi Simone,

While you were away some users have opened other issues and feature request.
I opened a [PR](https://github.com/zanza00/random-theme-switcher/pull/7) which contains these updates.
Take a look at the readme if you want more informations.

When you'll have time to merge it and publish it you will definitely make users happy ! 😉

Good Weekend ! 😊👋🏻
