### ISSUE TITLE
Set Interval for switching

### ISSUE THREAD

**Issue by Sylk** [zanza00/random-theme-switcher#9]
There should be an option that triggers every x minutes to swap a theme.

**Comment by Denis-net** [comment]
Hi @Sylk !

I have opened a pull request for switching the theme once a day.
Now I have improved my design based o your request.

The modes will be:

manual,
startup,
daily,
interval

I also added the `SwitchInterval` setting that will range between 3 minutes and one day.

Hope he will find time to merge it. 🤞🏻
